"""Type stubs for the regipy_rs Rust extension module."""

from collections.abc import Iterator
from typing import Any

class ParsingError(Exception):
    """Raised when hive parsing fails."""

    ...

class NKRecord:
    """Wrapper for a registry key (NK record)."""

    name: str
    class_name: str
    nk_offset: int
    subkey_count: int
    values_count: int
    last_modified: int

    def get_subkey(self, name: str) -> NKRecord | None: ...
    def get_value(self, name: str) -> tuple[str, int, Any, bool, bool] | None: ...
    def iter_subkeys(self) -> Iterator[NKRecord]: ...
    def iter_values(self) -> Iterator[tuple[str, int, Any, bool, bool]]: ...
    def header_dict(self) -> dict[str, Any]: ...

class RegistryHive:
    """Rust-backed registry hive parser."""

    def __init__(self, path: str): ...
    def root(self) -> NKRecord: ...
    def get_key(self, path: str) -> NKRecord: ...
    def get_subkey_at(self, path: str, name: str) -> NKRecord | None: ...
    def iter_subkeys_at(self, path: str) -> Iterator[NKRecord]: ...
    def iter_values_at(self, path: str) -> Iterator[tuple[str, int, Any, bool, bool]]: ...
    def recurse_subkeys(self) -> Iterator[NKRecord]: ...
    def walk_stats(self) -> dict[str, int]: ...
    def header_dict(self) -> dict[str, Any]: ...
    def wintime_to_iso(self, filetime: int) -> str: ...

class KeyIter:
    """Iterator over subkeys."""
    def __iter__(self) -> Iterator[NKRecord]: ...

class WalkIter:
    """Iterator over all keys in the hive."""
    def __iter__(self) -> Iterator[NKRecord]: ...
